# Generated by Django 4.0.6 on 2022-07-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('year', models.IntegerField()),
                ('verified', models.BooleanField(default=False, null=True)),
                ('field_of_study', models.CharField(max_length=50)),
            ],
        ),
    ]
