# Generated by Django 4.0.6 on 2022-07-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_student'),
        ('main', '0003_remove_reservation_attendance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
